package Servlets;

import java.io.IOException;
import java.io.OutputStream;
import java.io.PrintWriter;
import java.util.Date;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import entities.Supplier;

/**
 * Servlet implementation class createReportServlet
 */
@WebServlet("/createReportServlet")
public class createReportServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
    public createReportServlet() {
        super();
        // TODO Auto-generated constructor stub
    }

	/**
	 * @see HttpServlet#doGet(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		//response.getWriter().append("Served at: ").append(request.getContextPath());
		
	response.setContentType("text/plain");
	response.setHeader("Content-Disposition", "attachment; filename=\report.txt");
	try {
		HttpSession mysession=request.getSession();
		Supplier loggedin = (Supplier)request.getSession().getAttribute("currentSupplier");
		
		OutputStream output=response.getOutputStream();
		Date theDate=new Date();
		String title=request.getParameter("reportTitle");
		String productfor = "\n"+"Product: "+request.getParameter("reportProduct");
		String transaction = "\n"+"Transaction: "+(String)request.getParameter("TransType");
		String details = "\n"+"DETAILS: "+request.getParameter("notes");

		title+="\n\n----------------------------------------------\n\n\n";
		
		String timegenerated="Report generated at: "+theDate.toString();
		timegenerated+= ("\n"+"Report generated by: \n");
		timegenerated+= ("Supplier Name: "+loggedin.getName() + "\n"+"Supplier Username: "+loggedin.getUsername()+"\n");
		
		String result=("\n"+"------------------------"+"\n")+title+timegenerated+"\n"+productfor+"\n"+transaction+"\n"+details+"\n"+"---------end of report----------";
		output.write(result.getBytes());
		output.flush();
		output.close();
	}catch(Exception e) {
		System.out.println(e.getMessage());
	}
	}

	/**
	 * @see HttpServlet#doPost(HttpServletRequest request, HttpServletResponse response)
	 */
	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO Auto-generated method stub
		doGet(request, response);
	}

}
